# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 669)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1169, 669))
        MainWindow.setMaximumSize(QtCore.QSize(1169, 669))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 20, 20, 591))
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 201, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.completeness = QtWidgets.QLabel(self.groupBox_2)
        self.completeness.setGeometry(QtCore.QRect(0, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.completeness.setFont(font)
        self.completeness.setTextFormat(QtCore.Qt.AutoText)
        self.completeness.setScaledContents(False)
        self.completeness.setAlignment(QtCore.Qt.AlignCenter)
        self.completeness.setObjectName("completeness")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 300, 201, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.reference = QtWidgets.QPushButton(self.groupBox_3)
        self.reference.setGeometry(QtCore.QRect(90, 10, 101, 28))
        self.reference.setStyleSheet("color: rgb(255, 85, 0);")
        self.reference.setObjectName("reference")
        self.clear = QtWidgets.QPushButton(self.groupBox_3)
        self.clear.setGeometry(QtCore.QRect(10, 10, 71, 28))
        self.clear.setObjectName("clear")
        self.previous = QtWidgets.QPushButton(self.groupBox_3)
        self.previous.setGeometry(QtCore.QRect(10, 40, 71, 28))
        self.previous.setObjectName("previous")
        self.next = QtWidgets.QPushButton(self.groupBox_3)
        self.next.setGeometry(QtCore.QRect(90, 40, 101, 28))
        self.next.setObjectName("next")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 390, 181, 221))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tips_5 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tips_5.setFont(font)
        self.tips_5.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips_5.setObjectName("tips_5")
        self.verticalLayout.addWidget(self.tips_5)
        self.tips_7 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tips_7.setFont(font)
        self.tips_7.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips_7.setObjectName("tips_7")
        self.verticalLayout.addWidget(self.tips_7)
        self.tips_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.tips_2.setFont(font)
        self.tips_2.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips_2.setObjectName("tips_2")
        self.verticalLayout.addWidget(self.tips_2)
        self.tips_6 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.tips_6.setFont(font)
        self.tips_6.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips_6.setObjectName("tips_6")
        self.verticalLayout.addWidget(self.tips_6)
        self.tips = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tips.setFont(font)
        self.tips.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips.setObjectName("tips")
        self.verticalLayout.addWidget(self.tips)
        self.tips_3 = QtWidgets.QLabel(self.groupBox_4)
        self.tips_3.setObjectName("tips_3")
        self.verticalLayout.addWidget(self.tips_3)
        self.finished_and_next_image_buttton = QtWidgets.QPushButton(self.centralwidget)
        self.finished_and_next_image_buttton.setGeometry(QtCore.QRect(20, 220, 201, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.finished_and_next_image_buttton.setFont(font)
        self.finished_and_next_image_buttton.setObjectName("finished_and_next_image_buttton")
        self.warning_button = QtWidgets.QPushButton(self.centralwidget)
        self.warning_button.setGeometry(QtCore.QRect(20, 220, 201, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.warning_button.setFont(font)
        self.warning_button.setStyleSheet("background:rgb(255, 170, 127)")
        self.warning_button.setObjectName("warning_button")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(40, 110, 151, 61))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 170, 121, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.groupBox_4.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.line.raise_()
        self.finished_and_next_image_buttton.raise_()
        self.warning_button.raise_()
        self.logo.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.completeness.setText(_translate("MainWindow", "sample"))
        self.reference.setText(_translate("MainWindow", "标哪里？(F1)"))
        self.clear.setText(_translate("MainWindow", "清空全部"))
        self.previous.setText(_translate("MainWindow", "上一张"))
        self.next.setText(_translate("MainWindow", "下一张"))
        self.label_2.setText(_translate("MainWindow", "请尽量紧贴文字"))
        self.tips_5.setText(_translate("MainWindow", "放缩：鼠标滚轮"))
        self.tips_7.setText(_translate("MainWindow", "平移：鼠标滚轮或alt"))
        self.tips_2.setText(_translate("MainWindow", "选框确认：enter"))
        self.tips_6.setText(_translate("MainWindow", "选框取消：鼠标右键"))
        self.tips.setText(_translate("MainWindow", "撤回：cirl+z"))
        self.tips_3.setText(_translate("MainWindow", "删除：摁住ctrl\n"
"选择待删除框,摁delete"))
        self.finished_and_next_image_buttton.setText(_translate("MainWindow", "开始)"))
        self.warning_button.setText(_translate("MainWindow", "无标注，确认完成\n"
"(shift+enter)"))
        self.label.setText(_translate("MainWindow", "QQ1171132179"))

